### PR TITLE
Root float support.

### PR DESCRIPTION
**Pull request by inkdot7**
I just had to try...  Tested with a single-value float branch only...  I got a nice-looking plot.

Did some extra macros in `RootImpl::BindBranch()` and `RootImpl::Buffer()`

Should do similar `RootImpl::GetData()`?

The addition of a `bufd` array was perhaps not so nice?

### CODE REVIEW

**Comment by inkdot7** [comment]
Hmm, I should admit that testing `hist("YY", Tot)` does segfault in `RootImpl::Buffer()`...

**Comment by inkdot7** [comment]
Update:
```
//hist("XX", Pi1t)
hist("YY", Tot)
```
as well as
```
hist("XX", Pi1t)
//hist("YY", Tot)
```
works (give spectra that look not crazy), but not with both enabled.  The one with array (`ToT`), gives a bunch of warnings, however:
`node_signal.cpp:158:Tot: Signal check failed: (1U=1 >= len_=2).`

**Comment by inkdot7** [comment]
The segfault in `RootImpl::Buffer()` was due to some missing code in `RootImpl::Copy`.  Added fix in additional commit for the time being.  Now instead, it is able to trigger issues in the plotting:
```
hist("XX", Pi1t)
hist("XX2", Pi1e)
```
Triggered:
```
#4  0x00005555556010a2 in ImPlutt::Window::PlotHist1<unsigned int> (this=0x555557a53630, a_plot=0x7fffffffdd80, a_min=-inf, a_max=inf, 
    a_vec=std::vector of length 200, capacity 200 = {...}, a_bins=200) at implutt.cpp:2088
2088            assert(i0 < i1);
(gdb) print i0
$1 = 9223372036854775808
(gdb) print i1
$2 = 9223372036854775808
(gdb) print a_bins
$3 = 200
(gdb) print a_min
$4 = -inf
(gdb) print a_max
$5 = inf
(gdb) quit
```
and 
```
hist("XX", Pi1t)
hist("XX2", Pi2t)
```
finds:
```
#4  0x0000555555627862 in PlotHist::Fill (this=0x55555574ffe0, a_type=Value::kDouble, a_x=...) at plot.cpp:430
430       assert(i < m_axis.bins);
(gdb) print i
$1 = 0
(gdb) print m_axis_bins
No symbol "m_axis_bins" in current context.
(gdb) print m_axis.bins
$2 = 0
```

**Comment by hanstt** [comment]
-) I'll skip the "Non-impl" extra print-outs because it's in the exception message. I should make a proper "die" thing instead of the repeating cerr+throw now that this program is actually used by others.
-) Sorry for all the TTreeReader's, but they're difficult to generalize. The old SetBranch* stuff had other problems, but might consider that. Pointers rather than instantiated objects in some places might be more manageable in the long run too, I'm mainly trying some C++-isms which is never a good idea.
-) I will make a TTree generator in the tests when root is compiled in, that does most types and classes of primitives.

**Comment by inkdot7** [comment]
> -) I'll skip the "Non-impl" extra print-outs because it's in the exception message. I should make a proper "die" thing instead of the repeating cerr+throw now that this program is actually used by others.

ok, I just did not see any file:line marks, but perhaps did not look closely enough.  grepping the error message gave multiple hits so that was the reason

> -) Sorry for all the TTreeReader's, but they're difficult to generalize. The old SetBranch* stuff had other problems, but might consider that. Pointers rather than instantiated objects in some places might be more manageable in the long run too, I'm mainly trying some C++-isms which is never a good idea.

This TTreeReader thing looked pretty manageable and seems to handle types too, so probably less likely to give issues (by not allowing mistakes) than the SetBranch* stuff.

> 
> -) I will make a TTree generator in the tests when root is compiled in, that does most types and classes of primitives.

hehe, include some inf, -inf and nan values as well in the data :-)

**Comment by hanstt** [comment]
> > -) I will make a TTree generator in the tests when root is compiled in, that does most types and classes of primitives.
> 
> hehe, include some inf, -inf and nan values as well in the data :-)

I'll need help here when the test is ready, since I won't be as nasty as other users :p

**Comment by hanstt** [comment]
I snuck in your changes, and couldn't help myself from doing a bunch of other things on the way:
-) Unified buf/bufd with a union, by moving Type/Scalar from Value to Input, so there's a single place for types. This rattled a looot of files...
-) The val/arr float/double copies and dtors were permuted wrongly, again caused weird errors (:
-) Changed to ROOT types in the readers, there was a complaint about mismatching uint64_t with ULong_t.
And some other small things, will make a nicer "die" feature next so all request commits are taken care of somehow.

**Pull request closed without merging**
